permissions:
  contents: read

name: Security Scan

on:
  - push
  - pull_request

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Run Bandit
        run: bandit -r . -ll

      - name: Run Safety CLI to check for vulnerabilities
        uses: pyupio/safety-action@v1
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}

      - name: Django Security Checks
        env:
          DEBUG: False
          DJANGO_ALLOWED_HOSTS: "example.com"
          PYTHONPATH: src
        run: python manage.py check --deploy
